name: Build

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 8.0.x

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Use Xcode version 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      - name: Restore workloads
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore jc-google-mobile-ads-ios.sln
      - name: Build
        run: dotnet build jc-google-mobile-ads-ios.sln --no-restore
